### ISSUE TITLE
Cannot find module 'journey'

### ISSUE THREAD

**Issue by onsela** [cloudhead/journey#24]
This is what I got on the require function.

Stack:
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'journey'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/onsela/Documents/Nodejs/journey_test.js:1:77)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)

**Comment by onsela** [comment]
Ok my bad. Closed, sorry.
